version: '3.1'
services:
  worker:
    build: .
    restart: always
    volumes:
      - /path/to/vaultwarden/files/:/vault
      - /path/to/vaultwarden/backups:/backups
    env_file:
      - /path/to/backup.env
